# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{attest}
  s.version = "0.1.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Alan Skorkin"]
  s.date = %q{2010-11-18}
  s.default_executable = %q{attest}
  s.description = %q{Attest allows you to define tests inline and treat classes modules and random methods as first class citizens}
  s.email = %q{alan@skorks.com}
  s.executables = ["attest"]
  s.extra_rdoc_files = [
    "LICENSE",
     "README.rdoc"
  ]
  s.files = [
    ".document",
     ".gitignore",
     "Gemfile",
     "Gemfile.lock",
     "LICENSE",
     "README.rdoc",
     "Rakefile",
     "VERSION",
     "attest.gemspec",
     "bin/attest",
     "doodle.txt",
     "lib/attest.rb",
     "lib/attest/attest_error.rb",
     "lib/attest/config.rb",
     "lib/attest/core_ext/kernel.rb",
     "lib/attest/core_ext/object.rb",
     "lib/attest/execution_context.rb",
     "lib/attest/expectation_result.rb",
     "lib/attest/itself.rb",
     "lib/attest/output/basic_output_writer.rb",
     "lib/attest/test_container.rb",
     "lib/attest/test_object.rb",
     "lib/attest/test_parser.rb",
     "test/another_testclass.rb",
     "test/more/third_test.rb",
     "test/testclass.rb"
  ]
  s.homepage = %q{http://github.com/skorks/attest}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.7}
  s.summary = %q{An inline testing framework}
  s.test_files = [
    "test/more/third_test.rb",
     "test/another_testclass.rb",
     "test/testclass.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<trollop>, [">= 0"])
      s.add_development_dependency(%q<mocha>, [">= 0"])
    else
      s.add_dependency(%q<trollop>, [">= 0"])
      s.add_dependency(%q<mocha>, [">= 0"])
    end
  else
    s.add_dependency(%q<trollop>, [">= 0"])
    s.add_dependency(%q<mocha>, [">= 0"])
  end
end

